"%dev":
  quarkus:
    http:
      port: 8080
    datasource:
      db-kind: postgresql
      db-version: 17
    flyway:
      migrate-at-start: true
  mp:
    jwt:
      verify:
        issuer: eventman
        publickey:
          location: ../jwt/publicKey.pem